version: 2
updates:
#  - package-ecosystem: "gomod"
#    directory: "/"
#    schedule:
#      interval: "daily"
#    commit-message:
#      prefix: "chore(deps)"
#      include: "scope"
#    labels:
#      - "ğŸ¤– Dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    labels:
      - "ğŸ¤– Dependencies"
      - "ğŸ—ï¸ CI/CD & Infrastructure"